receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch/traces:
    timeout: 1s
    send_batch_size: 50
  batch/metrics:
    timeout: 60s

  filter/drop_healthcheck_attributes:
    traces:
      span:
        - 'IsMatch(attributes["url.path"], ".*healthcheck.*")'
        - 'IsMatch(attributes["http.target"], ".*healthcheck.*")'
        - 'IsMatch(attributes["http.route"], ".*healthcheck.*")'

  tail_sampling:
    policies: [
      {
        name: error-traces,
        type: status_code,
        status_code: { status_codes: [ ERROR ] }
      },
      {
        name: normal-traces,
        type: probabilistic,
        probabilistic: { sampling_percentage: 5 }
      },
    ]

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"
    path: "/health"
    response_body:
      healthy: "UP"
      unhealthy: "DOWN"

exporters:
  awsxray:
  awsemf:
    namespace: ECS/AWSOTel/Application
    log_group_name: '/aws/ecs/application/metrics'
  debug:
    verbosity: detailed
service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch/traces,filter/drop_healthcheck_attributes,tail_sampling]
      exporters: [debug,awsxray]
    metrics:
      receivers: [otlp]
      processors: [batch/metrics]
      exporters: [awsemf]

